### ISSUE TITLE
Handler Thread is Leaked

### ISSUE THREAD

**Issue by eygraber** [Doctoror/RxCursorLoader#4]
Every subscription will start a `HandlerThread` that is never stopped by running `quit`.

**Comment by eygraber** [comment]
It also may be helpful to allow passing a `HandlerThread` to use.

**Comment by Doctoror** [comment]
Thank you for this report.
It is fixed in version `2.0.4`. This version is being deployed to Maven and will be available soon.

> It also may be helpful to allow passing a HandlerThread to use.

The `HandlerThread` is created to ensure `onNext` and `onError` in `emitter` are called from the same thread `ObservableOnSubscribe.subscribe` was called with, thus passing it will not make any sense for external APIs.

**Comment by eygraber** [comment]
Awesome :+1: 

`onNext` and `onError` only need to be called from the same thread as `subscribe` on a per subscriber basis, so passing in a `HandlerThread` would still make sense.

For example, I can call `RxCursorLoader.create(contentResolver, query, handlerThread)` where `handlerThread` is something I manage. The benefit of this is not having to create a new thread every time I call `RxCursorLoader.create` if I don't want to (I can pass in a `HandlerThread` that I reuse throughout my app).

**Comment by Doctoror** [comment]
The `HandlerThread` is designed to ensure the same `Thread `as the `ObservableOnSubscribe.subscribe` is used. This thread should be the same as the thread used by `subscribeOn` `Scheduler` (if I implemented this right).

**Comment by eygraber** [comment]
Based on what you have now, `onNext` and `onError` will not be called on the same thread as `subscribe`. `subscribe` will be called on whatever thread the caller is on (or whatever thread is specified by `subscribeOn`; which the library doesn't call).

In `subscribe` (which runs every time the observable is subscribed to), a new `HandlerThread` is being created (which creates a new thread), and a `Handler` to it's `Looper` is being passed to the `ContentObserver`, which means that `onNext` and `onError` will be called on that `HandlerThread`, and not the thread that `subscribe` was called on.

This also means that if `subscribe` is called on the main thread, and no `subscribeOn` is specified, the initial query will be run on the main thread.

My suggestion would be to pass in a `HandlerThread` for the sole purpose of not having to create a new one each time `subscribe` is called. I'd also suggest calling `subscribeOn(AndroidSchedulers.from(handlerThread.getLooper()))` so that `subscribe` happens on that background thread, and document that `onNext` / `onError` will be emitted on a background `HandlerThread` so users are aware of it.

**Comment by Doctoror** [comment]
> new HandlerThread is being created (which creates a new thread)

Just checked this. You are right. This was not my intention. I wanted to use the Looper of the Thread `subscribeOn` was called from. I will look on how can I rework that.

**Comment by Doctoror** [comment]
@eygraber in 2.1.0, I've added a `flowable` method, which accepts both `Scheduler` and `BackpressureStrategy`. `scheduleDirect` will be used on the supplied `Scheduler` to run query and emit `onNext`. Unfortunately, since `ContentObserver` still requires a `Handler`, `HandlerThread` will still be used. However, I will not expose the `HandlerThread` API to users, because this is an implementation detail that is subject to change, and is not a part of the API.
